### ISSUE TITLE
How to handle DownForMaintenance exceptions

### ISSUE THREAD

**Issue by Fraaankes** [braintree/braintree_dotnet#92]
### General information

* SDK/Library version: 4.8.0
* Environment: Production
* Language, language version, and OS: .NET 4.7 on Windows 10

### Issue description

We are seeing some of these exceptions during your "maintenance windows":
```
Braintree.Exceptions.DownForMaintenanceException: Exception of type 'Braintree.Exceptions.DownForMaintenanceException' was thrown.
  at Braintree.HttpService.ThrowExceptionIfErrorStatusCode(HttpStatusCode httpStatusCode, String message)
  at Braintree.HttpService.<GetHttpResponseAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at Braintree.BraintreeService.<GetXmlResponseAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
  at Braintree.CustomerGateway.<FindAsync>d__5.MoveNext()
```

But here it says it should never happen anymore:
https://developers.braintreepayments.com/reference/general/exceptions/dotnet#down-for-maintenance

But it doesnt mention how a merchant should handle the exception. Since you are technically down, should the request just be abandoned ?

**Comment by hollabaq86** [comment]
👋 @Fraaankes, thanks for reaching out. As our documentation states, we have to keep the name for this exception `DownForMaintenance` to maintain backwards compatibility. We'll change the name when we make a major version update. This kind of exception is thrown for [HTTP Status](https://github.com/braintree/braintree_dotnet/blob/fa9913949e2d1f8eeded210973f139f162b43baf/src/Braintree/HttpService.cs#L350-L351) `ServiceUnavailable` or a 503.

This type of response doesn't necessarily mean that we are _down_, but that our API was unavailable at the time of your request. You could retry the same request to see if you receive a successful response. 

If you ever do encounter a period of 503 responses from Braintree, you absolutely should [contact Support](https://help.braintreepayments.com/) with timestamps and the type of API calls you are making so that we can investigate. Additionally, I recommend subscribing to our [Status Site](https://status.braintreepayments.com/) so that you are made aware of any issues.

I'll leave feedback with our docs team to make this more clear in the section you referenced.
